### ISSUE TITLE
Registration form with <select> element instead of radio buttons?

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/library#3]
Do you guys happen to have any code laying around for rendering subscription levels on the registration form as a select list instead of radio buttons? I'm able to generate the elements just fine, but can't seem to get the right attributes/names/etc. for RCP to recognize it as valid – I get the `No available subscription levels for your account.` message on the form.

**Comment by tnorthcutt** [comment]
Aaaand I just figured out I'll have to replace `register.js`to make this work, so I'm guessing there won't be any drop-in code snippets for this 😕

**Comment by pippinsplugins** [comment]
@tnorthcutt how come you have to replace register.js for it? I'd love to support this properly.

**Comment by tnorthcutt** [comment]
@pippinsplugins because `register.js` is targeting the `input` elements specifically, for instance:

```
// RCP code
var level    = $( '#rcp_subscription_levels input:checked' );

// Modified to work with <select>
var level    = $( '#rcp_subscription_levels option:selected' );
```

**Comment by tnorthcutt** [comment]
Ok, this seems to work in `rcp_calc_total()` so I assume it would as well in the other spots:

```
var subscription = ( $('#rcp_subscription_levels :checked').length ) ? $('#rcp_subscription_levels :checked').val() : $('input[name="rcp_level"]').val();
```

In that case and other spots we're checking for `:checked` and if not present getting the value of the first `input[name="rcp_level"]`, obviously with a `<select>` list we would no longer have an `<input>`... but perhaps that's fine since with the select, there's always a `:checked` element? Although if someone builds a `<select>` with an empty first option, e.g. "Choose your plan" as an `<option>`, that wouldn't work. Not sure how to address that situation without some semi-hacky conditionals in the js to see what kind of html we're working with.

**Comment by tnorthcutt** [comment]
So that works if you have _one_ select list... I have three (b/c I'm grouping the subscription levels by "tier", e.g. bronze/silver/gold. Trying to see if I can get it working with that structure as well.
