### ISSUE TITLE
Allow restricted page content in search but require log in when clicked

### ISSUE THREAD

**Issue by damianetg** [restrictcontentpro/library#69]
Hi guys,

Any pages restricted by Restrict Content Pro do not appear in search when logged out/not a member. Is it possible to have them appear in search, but redirect to the Restricted page when clicked on?

Damiane

**Comment by nosegraze** [comment]
Hi @damianetg ,

Can you please contact our support team here to discuss: https://restrictcontentpro.com/support/ ?

Thanks!
